### ISSUE TITLE
Menu layout change 

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#155]
Make the randomization tests and bootstrapping an option within the meta-analysis and meta-regression menu.

**Comment by gdietz** [comment]
Are we sure about this? How does this jive with issue #150? I think it might be reasonable to do either one or the other but not both. Personally, I'm in favor of just doing issue #150 (including normal meta-analysis / regression results on the randomization results output). We have plans to include additional plots, etc. on the randomization output in the future and combining all the different output together from various analyses happening at once would make a very confusing display. I think it is easier for the user to understand what they are doing if they choose a single analysis to perform and get the results of a single analysis out, rather than do a few analyses at once.

**Comment by gdietz** [comment]
We decided not to do this in favor of issue issue #150.
