### ISSUE TITLE
Yell at user if they input studies with 0 variance

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#159]
And actually prevent this from actually happening.

**Comment by gdietz** [comment]
How about we just not allow the user to include that study in an analysis much like we do now when there is no effect size or variance?

**Comment by bwallace** [comment]
Seems reasonable

**Comment by gdietz** [comment]
Now, we disallow including a study if the variance is within a certain small range (+/- 10^-6)

**Comment by JGurevitch** [comment]
A good solution.
It would be good to have something pop up that says, "studies 73, 84 and
99A were excluded due to missing effect sizes or zero variances" but then
go ahead and do the analysis omitting them.

On Sun, Jan 4, 2015 at 7:28 PM, George Dietz <notifications@github.com>
wrote:

> How about we just not allow the user to include that study in an analysis
> much like we do now when there is no effect size or variance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/159#issuecomment-68656817>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by JGurevitch** [comment]
Still sounds reasonable.

On Sun, Jan 4, 2015 at 7:55 PM, George Dietz <notifications@github.com>
wrote:

> Now, we disallow including a study if the variance is within a certain
> small range (+/- 10^-6)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/159#issuecomment-68657831>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
