### ISSUE TITLE
Subsume OpenMetaAnalyst into OpenMEE

### ISSUE THREAD

**Issue by gdietz** [gdietz/OpenMEE#167]
Instead of maintaining to separate but very related programs, we should combine the two to use a common python codebase. To distinguish the behavior, we could have a global 'mode' switch that would be set one way or the other when making builds to generate OpenMetaAnalyst or OpenMEE.
Combining them would make it easier to address issues relating operational issues with the program e.g. not great unicode support, data management issues etc. It would also make adding the same new feature/analysis etc to both programs easier.

To do this, we would have to add a few features present in OpenMetaAnalyst not present in OpenMEE (e.g. diagnostic meta analysis, etc).

**Comment by JGurevitch** [comment]
Can you explain this in more detail? What are the diagnostics, etc. in
OpenMetaAnalyst? If you mean combining things so that users don't have to
keep circling back through the menu multiple times to get one set of
commonly needed output, that is what we've been hoping for, for some time.

On Sun, Mar 8, 2015 at 8:56 PM, George Dietz <notifications@github.com>
wrote:

> Instead of maintaining to separate but very related programs, we should
> combine the two to use a common python codebase. To distinguish the
> behavior, we could have a global 'mode' switch that would be set one way or
> the other when making builds to generate OpenMetaAnalyst or OpenMEE.
> Combining them would make it easier to address issues relating operational
> issues with the program e.g. not great unicode support, data management
> issues etc.
>
> To do this, we would have to add few features present in OpenMetaAnalyst
> not present in OpenMEE (e.g. diagnostic meta analysis, etc).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/167>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gdietz** [comment]
closing this since its sort of vague.
