### ISSUE TITLE
weighted histograms seems to be failing or not showing up?

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#208]

**Comment by bwallace** [comment]
File "/Users/byron/dev/OpenMEE/python_to_R.py", line 69, in execute_in_R
    raise CrazyRError("Some crazy R error occurred: %s" % str(e))
ome_globals.CrazyRError: Some crazy R error occurred: Error in weighted.histogram(data = tmp_obj) : 
  unused argument (data = tmp_obj)
: None

**Comment by gdietz** [comment]
seems to be working for me, when's the last time you reinstalled the R package?

**Comment by JGurevitch** [comment]
This may have been from a user experience. Perhaps it doesn't work on all
platforms. It does work for me.

On Wed, May 11, 2016 at 7:55 AM, George Dietz <notifications@github.com>
wrote:

> seems to be working for me, when's the last time you reinstalled the R
> package?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/208#issuecomment-218437750>
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gdietz** [comment]
@bwallace I tested this from source and in the current mac build. The current mac build didn't seem to launch strangely. But I made a new one and uploaded it so it should be ok now. I think perhaps R got stuck installing openmeer to my local R library instead of root. Anyway, i cleaned it up. Closing this for now. Can reopen if issue doesn't seem to have gone away.
